### ISSUE TITLE
Error when testing app

### ISSUE THREAD

**Issue by heeenkie** [Digitusmedia/explora-dora#22]
Hi everyone,
I am peer reviewing your app.

I think you have an error when register to your app. The button creates the following alert: 
Firebase: Error (auth/invalid-email).

Can you provide me an existing account to test or am I doing something wrong?

@ThorNilsson @Digitusmedia @janetzky @MiniMarius

**Comment by ThorNilsson** [comment]
No problem, you can use mine. 
Mail: thor@thor.com
pass: nilsson

**Comment by ThorNilsson** [comment]
In progress View, you can scroll to Uppsala to see a few tests

**Comment by heeenkie** [comment]
Sorry for being retarded when trying to register. I didn't expect the view to be the same for both register and login so I clicked register without values. I mentioned  that as an interaction improvement. Good job!
